#!/usr/bin/with-contenv sh

set -e

if [ -f /firstrun ]; then
  s6-echo "[i] Configure PHP."
  sed -i "s*include /etc/nginx/headers.conf\;*include /etc/nginx/headers.conf\;\n        include /etc/nginx/fpm.conf\;\n\n        root /usr/share/webapps\;\n        index index.php\;*g" /etc/nginx/localhost.site
  mv /nginx_fpm.conf /etc/nginx/fpm.conf
  rm /firstrun
fi

exit 0
