#!/bin/sh

exec /usr/bin/mysqld_safe \
  --log-warnings \
  --slow-query-log \
  --slow-query-log-file=/dev/stdout \
  --general-log \
  --general-log-file=/dev/stdout \
  --log-bin-trust-function-creators=1
