#!/usr/bin/with-contenv sh

set -e

if [ "$(ls -A /usr/share/webapps/)" ]; then
  echo "[i] File(s) found in webapps folder."
else
  echo "[i] Create PHP info page."
  echo "<?PHP\nphpinfo ();\n?>" -e > /usr/share/webapps/index.php
  s6-envuidgid www-data s6-chown -U -- /usr/share/webapps/index.php
fi

exit 0
