#!/usr/bin/with-contenv sh

set -e

if [ ! -d /tmp ]; then
  mkdir /tmp
  chmod 777 /tmp
fi

if [ -f /firstrun ]; then
  s6-echo "[i] Configure PHP."

# NGINX
  if [ -f /usr/sbin/nginx ]; then
    sed -i "s*include /etc/nginx/headers.conf\;*include /etc/nginx/headers.conf\;\n        include /etc/nginx/fpm.conf\;\n\n        root /usr/share/webapps\;\n        index index.php\;*g" /etc/nginx/localhost.site
    mv /nginx_fpm.conf /etc/nginx/fpm.conf
  fi

# Apache
  if [ -f /usr/sbin/apache2 ]; then
    apt-get purge -y php7.0-fpm
    apt-get update
    apt-get install -y libapache2-mod-php7.0
    s6-rmrf /etc/php/7.0/fpm
    s6-rmrf /nginx_fpm.conf
    s6-rmrf /etc/services.d/php-fpm
    a2dissite 000-default
    cp -a /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-enabled/000-default.conf
    sed -i "s*/var/www/html*/usr/share/webapps*" /etc/apache2/sites-enabled/000-default.conf
    a2dissite default-ssl
    cp -a /etc/apache2/sites-available/default-ssl.conf /etc/apache2/sites-enabled/default-ssl.conf
    sed -i "s*/var/www/html*/usr/share/webapps*" /etc/apache2/sites-enabled/default-ssl.conf
  fi
  rm /firstrun
fi

exit 0
