version: '2'

services:
  redis:
    restart: always
    container_name: moodle_redis
    hostname: redis
    image: maxder/alpine-redis:x86_64
  mariadb:
    restart: always
    container_name: moodle_db
    hostname: mariadb
    image: maxder/alpine-mariadb:x86_64
    volumes:
    - /srv/docker/moodle/db:/var/lib/mysql
    environment:
    - DBUSER=dbadmin
    - DBPASS=dbadminpass
  moodle:
    restart: always
    container_name: moodle
    hostname: moodle
    image: maxder/debian-moodle:x86_64
    ports:
    - 80:80
    - 443:443
    volumes:
    - /srv/docker/moodle/data:/moodledata
    - /srv/docker/moodle/apache/tls:/etc/apache2/tls
    - /srv/docker/moodle/apache/sites-enabled:/etc/apache2/sites-enabled
    environment:
    - DBUSER=dbadmin
    - DBPASS=dbadminpass
    #- SUBDIR=moodle ## Moodle in a subfolder.
    - WWWROOT=https://localhost ## Your domain or IP address here
    - INSTALL=silent ## Silent installation via CLI. See docker logs for admin password (docker logs moodle)
    depends_on:
    - mariadb
    - redis
    links:
    - mariadb:db
    - redis:redis
