#!/usr/bin/env bash
# ------------------------------------------------------------------
# [Christian-Maximilian Steier]
# Build a small AlpineLinux Docker image based with ownCloud        
# ------------------------------------------------------------------

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NAMESPACE="maxder"

if [ $(uname -m) == "armv6l" ]; then
	DISTRO="rpi-alpine"
	COUNT="1"
else
	DISTRO="alpine"
	COUNT="2"
fi
sed -i "s*PLACEHOLDER*${DISTRO}*g" $DIR/Dockerfile
sed -i "s*COUNT**${COUNT}*g" $DIR/conf/nginx.conf

CONTAINER_NAME="owncloud"
IMAGENAME="${NAMESPACE}/${DISTRO}-${CONTAINER_NAME}:edge"

build() {
  docker build --rm -t $IMAGENAME .

  [ $? != 0 ] && error "Docker image build failed !" && exit 100
}

run() {
if [ $(docker inspect -f {{.State.Running}} mysql) == "true" ]; then
  	docker run -d --hostname $CONTAINER_NAME --name $CONTAINER_NAME -p 80:80 --link mysql:db $IMAGENAME
	docker logs $CONTAINER_NAME
  [ $? != 0 ] && error "Docker image build failed !" && exit 100
else
        error "run first ${NAMESPACE}/${DISTRO}-mysql:edge" && exit 100
fi
}


stop() {
  docker stop $CONTAINER_NAME
}

start() {
  docker start $CONTAINER_NAME
}

remove() {
  log "Removing previous container $CONTAINER_NAME" && \
      docker rm -f $CONTAINER_NAME &> /dev/null || true
}

log() {
  echo -e "$BLUE > $1 $NORMAL"
}

error() {
  echo ""
  echo -e "$RED >>> ERROR - $1$NORMAL"
}

help() {
  echo "-----------------------------------------------------------------------"
  echo "                      Available commands                              -"
  echo "-----------------------------------------------------------------------"
  echo -e -n "$BLUE"
  echo "   > build - Build the Docker image"
  echo "   > stop - Stop $CONTAINER_NAME"
  echo "   > start - Start $CONTAINER_NAME"
  echo "   > remove - Remove $CONTAINER_NAME"
  echo "   > help - Display this help"
  echo -e -n "$NORMAL"
  echo "-----------------------------------------------------------------------"

}

# Output colors
NORMAL="\\033[0;39m"
RED="\\033[1;31m"
BLUE="\\033[1;34m"

$*
