FROM maxder/ubuntu-bbb-ffmpeg
MAINTAINER Christian-Maximilian

# Set locale to en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get install -y --force-yes bbb-freeswitch
