#!/usr/bin/with-contenv sh

set -e

SUBDIR=${SUBDIR:-}
APPDIR=/usr/share/webapps/${SUBDIR}
APPADMIN=${APPADMIN:-admin}
APPADMINPASS=${APPADMINPASS:-$(pwgen -s -1 8)}
APPADMINEMAIL=${APPADMINEMAIL:-admin@lochalhost.local}
APPDB=${APPDB:-moodle}
APPDBUSER=${APPDBUSER:-moodle}
APPDBPASS=${APPDBPASS:-$(pwgen -s -1 16)}
SALD=${SALD:-$(pwgen -s -1 16)}
WWWROOT=${WWWROOT:-http://localhost}
FULLNAME=${FULLNAME:-Moodle}
SHORTNAME=${SHORTNAME:-MOODLE}
SUMMARY=${SUMMARY:-Moodle}
DBUSER=${DBUSER:-$DB_ENV_DBUSER}
DBPASS=${DBPASS:-$DB_ENV_DBPASS}
DBHOST=${DBHOST:-db}
INSTALL=${INSTALL:-normal}

# Set max upload to 100 MB
sed -i -e "s/upload_max_filesize\s*=\s*2M/upload_max_filesize = 100M/g" /etc/php/7.0/apache2/php.ini
sed -i -e "s/post_max_size\s*=\s*8M/post_max_size = 100M/g" /etc/php/7.0/apache2/php.ini
sed -i -e "s/short_open_tag\s*=\s*Off/short_open_tag = On/g" /etc/php/7.0/apache2/php.ini

if [ ${SUBDIR} != "" ]; then
  if [ ! $SUBDIR = "moodle" ]; then
    mv /usr/share/webapps/moodle /usr/share/webapps/$SUBDIR
    chown www-data:www-data /usr/share/webapps/$SUBDIR
  fi
  if [ -f /etc/apache2/sites-enabled/000-default.conf ]; then
    sed -i "s*/usr/share/webapps/moodle*/usr/share/webapps*g" /etc/apache2/sites-enabled/000-default.conf
  fi
  if [ -f /etc/apache2/sites-enabled/default-ssl.conf ]; then
    sed -i "s*/usr/share/webapps/moodle*/usr/share/webapps*g" /etc/apache2/sites-enabled/default-ssl.conf
  fi
fi

if [ $INSTALL = "silent" ]; then
  echo "Create database user $APPDBUSER and database $APPDB"
  until nc -z ${DBHOST} 3306; do sleep 1; echo "Waiting for DB to come up..."; done
  mysql -u ${DBUSER} --password=${DBPASS} -h ${DBHOST} <<-EOF
  CREATE DATABASE IF NOT EXISTS $APPDB CHARACTER SET utf8;
  GRANT ALL PRIVILEGES ON $APPDB.* TO $APPDBUSER IDENTIFIED BY '$APPDBPASS';
  FLUSH PRIVILEGES;
  USE $APPDB;
  SET SESSION sql_mode=STRICT_ALL_TABLES;
  SET GLOBAL innodb_file_per_table=1;
  SET GLOBAL innodb_file_format=Barracuda;
EOF

  apt-get update
  apt-get install sudo
  if [ ! $SUBDIR = "" ]; then
    sudo -u www-data php $APPDIR/admin/cli/install.php \
        --non-interactive \
        --agree-license \
        --lang=en \
        --wwwroot=${WWWROOT}/${SUBDIR} \
        --dataroot=/var/moodledata \
        --dbtype=mariadb \
        --dbhost=${DBHOST} \
        --dbuser=${APPDBUSER} \
        --dbpass=${APPDBPASS} \
        --dbport=3306 \
        --fullname=${FULLNAME} \
        --shortname=${SHORTNAME} \
        --summary=${SUMMARY} \
        --adminuser=${APPADMIN} \
        --adminpass=${APPADMINPASS} \
        --adminemail=${APPADMINEMAIL}
    export SUDO_FORCE_REMOVE=yes
    apt-get purge -y sudo
    apt-get clean
  else
    sudo -u www-data php $APPDIR/admin/cli/install.php \
	--non-interactive \
	--agree-license \
	--lang=en \
	--wwwroot=${WWWROOT} \
	--dataroot=/var/moodledata \
	--dbtype=mariadb \
	--dbhost=${DBHOST} \
	--dbuser=${APPDBUSER} \
	--dbpass=${APPDBPASS} \
	--dbport=3306 \
	--fullname=${FULLNAME} \
	--shortname=${SHORTNAME} \
	--summary=${SUMMARY} \
	--adminuser=${APPADMIN} \
	--adminpass=${APPADMINPASS} \
	--adminemail=${APPADMINEMAIL}
    export SUDO_FORCE_REMOVE=yes
    apt-get purge -y sudo
    apt-get clean
  fi
  chown www-data:www-data $APPDIR/config.php
  echo "\n[i] Set automatic configuration:\n  Admin = $APPADMIN \n  Pass = $APPADMINPASS \n  www_root: $WWWROOT/${SUBDIR}\n---\n"
fi

if [ -f $APPDIR/config.php ] && [ -f /etc/moodle/config.php ]; then
  mv $APPDIR/config.php /etc/moodle/orig.config.php
  ln -s /etc/moodle/config.php $APPDIR/config.php
fi
if [ ! -f $APPDIR/config.php ] && [ -f /etc/moodle/config.php ]; then
  ln -s /etc/moodle/config.php $APPDIR/config.php
fi
if [ -f $APPDIR/config.php ] && [ ! -f /etc/moodle/config.php ]; then
  mv $APPDIR/config.php /etc/moodle/config.php
  ln -s /etc/moodle/config.php $APPDIR/config.php
fi
if [ ! -L /etc/moodle/lib ]; then
 ln -s $APPDIR/lib /etc/moodle/lib 
fi
rm /etc/cont-init.d/04-firstrun

exit 0
