version: '2'

services:
  oc_db:
    container_name: owncloud_db
    image: maxder/alpine-mariadb:x86_64
    dns:
    - "127.0.0.1"
    environment:
    - DBUSER=dbadmin
    - DBPASS=dbadmin
    volumes:
    - /srv/docker/owncloud/db:/var/lib/mysql
    restart: always

  oc:
    image: maxder/alpine-owncloud:x86_64
    container_name: owncloud
    ports:
    - "80:80"
    - "443:443"
    links:
    - oc_db:db
    environment:
    - OCADMIN=ocadmin
    - OCPASS=ocadmin
    volumes:
    - /srv/docker/owncloud/data:/var/owncloud/data
    - /srv/docker/owncloud/config:/usr/share/webapps/owncloud/config
    - /srv/docker/owncloud/www:/etc/nginx/sites-enabled
    - /srv/docker/owncloud/www/tls:/etc/nginx/tls 
    restart: always
