mysql:
  image: maxder/alpine-mysql:ARCHTAG
  ports:
    - "127.0.0.1:3306:3306"
  environment:
    - DBUSER=dbadmin
    - DBPASS=dbadmin
  volumes:
    - /srv/docker/mysql:/var/lib/mysql
  restart: always

redis-server:
  image: maxder/alpine-redis:ARCHTAG
  ports:
    - "6379:6379"
  volumes:
    - /srv/docker/redis:/var/lib/redis
  restart: always

owncloud:
  ports:
    - "80:80"
    - "443:443"
  links:
    - redis-server:redis
    - mysql:db
  environment:
    - OCADMIN=ocadmin
    - OCPASS=ocadmin
  volumes:
    - /srv/docker/owncloud/data:/var/owncloud/data
    - /srv/docker/owncloud/config:/usr/share/webapp/owncloud/config
    - /srv/docker/owncloud/www:/etc/nginx/sites-enabled
    - /srv/docker/owncloud/tls:/etc/nginx/tls 
  restart: always

