#!/bin/sh
set -e

if [ -f /firstrun ]; then

  ETHERPAD_DB_NAME=${ETHERPAD_DB_NAME:-etherpad}
  ETHERPAD_DB_USER=${ETHERPAD_DB_USER:-etherpad}
  ETHERPAD_DB_PASS=${ETHERPAD_DB_PASS:-$(pwgen -s -1 16)}
  ETHERPAD_TITLE=${ETHERPAD_TITLE:-Etherpad}
  ETHERPAD_SESSION_KEY=${ETHERPAD_SESSION_KEY:-$(
                node -p "require('crypto').randomBytes(32).toString('hex')")}
  ETHERPAD_ADMIN_USER=${ETHERPAD_ADMIN_USER:-admin}
  ETHERPAD_ADMIN_PASS=${ETHERPAD_ADMIN_PASS-$(pwgen -s -1 16)}
  DBADMIN=${DBADMIN:-$DB_ENV_DBUSER}
  DBPASS=${DBPASS:-$DB_ENV_DBPASS}
  DBHOST=${DBHOST:-$DB_PORT_3306_TCP_ADDR}
  eppath=/opt/etherpad-lite

  if [ -z "$DB_PORT_3306_TCP_ADDR" ]; then
	echo >&2 'error: missing MYSQL_PORT_3306_TCP environment variable'
	echo >&2 '  Did you forget to --link some_mysql_container:db ?'
	exit 1
  fi

  # Check if database already exists
  RESULT=`mysql -u${DBADMIN} -p${DBPASS} \
	-h${DBHOST} --skip-column-names \
	-e "SHOW DATABASES LIKE '${ETHERPAD_DB_NAME}'"`

  if [ "$RESULT" != $ETHERPAD_DB_NAME ]; then
	# mysql database does not exist, create it
	echo "Creating database ${ETHERPAD_DB_NAME}"

  mysql -u $DBADMIN --password=$DBPASS -h $DBHOST <<-EOF
      CREATE DATABASE IF NOT EXISTS ${ETHERPAD_DB_NAME} CHARACTER SET utf8;
      GRANT ALL PRIVILEGES ON ${ETHERPAD_DB_NAME}.* TO '$ETHERPAD_DB_USER'@'%' IDENTIFIED BY '$ETHERPAD_DB_PASS';
      FLUSH PRIVILEGES;
EOF

  fi


  if [ ! -f $eppath/settings.json ]; then
	cp $eppath/settings.json.template $eppath/settings.json

cat << EOF > /opt/etherpad-lite/settings.json
{
  "title": "${ETHERPAD_TITLE}",
  "ip": "0.0.0.0",
  "port" : 9001,
  "dbType" : "mysql",
  "dbSettings" : {
                    "user"    : "${ETHERPAD_DB_USER}", 
                    "host"    : "${DBHOST}", 
                    "password": "${ETHERPAD_DB_PASS}", 
                    "database": "${ETHERPAD_DB_NAME}"
                  },
EOF

cat << EOF >> /opt/etherpad-lite/settings.json
  "users": {
    "${ETHERPAD_ADMIN_USER}": {
      "password": "${ETHERPAD_ADMIN_PASS}",
      "is_admin": true
    }
  },
EOF

cat << EOF >> /opt/etherpad-lite/settings.json
}
EOF

  fi

echo -e "\n\n[i] Set automatic configuration:\n  APIKEY: $(cat /opt/etherpad-lite/APIKEY.txt)\n  ADMIN: $ETHERPAD_ADMIN_USER\n  PASS: $ETHERPAD_ADMIN_PASS\n---\n"

rm /firstrun
apk del pwgen mariadb-client

fi
