#!/usr/bin/env bash
# ------------------------------------------------------------------
# [Christian-Maximilian Steier]
# Build a small AlpineLinux Docker image with mahara        
# ------------------------------------------------------------------

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NAMESPACE="maxder"

if [ $(uname -m) == "armv6l" ]; then
	DISTRO="rpi-alpine"
else
	DISTRO="alpine"
fi
sed -i "s*PLACEHOLDER*${DISTRO}*g" $DIR/Dockerfile

CONTAINER_NAME="mahara"
IMAGENAME="${NAMESPACE}/${DISTRO}-${CONTAINER_NAME}:edge"

build() {
  docker build --rm -t $IMAGENAME .

  [ $? != 0 ] && error "Docker image build failed !" && exit 100
}

run() {

# At least three arguments should be present
if [[ "$#" < 2 ]]; then
	echo -e "You must specify at least two arguments: first is database user and second database password: \ndo run mahara password"
	exit 1
fi
  docker run -d --hostname $CONTAINER_NAME --name $CONTAINER_NAME -p 127.0.0.1:8086:80 -e MAHARA_DB=$1 -e MAHARA_PASS=$2 --link=mysql:db $IMAGENAME
  docker logs $CONTAINER_NAME
  [ $? != 0 ] && error "Docker image build failed !" && exit 100
}

silent() {
  docker run -d --hostname $CONTAINER_NAME --name $CONTAINER_NAME -p 127.0.0.1:8086:80 -e INSTALL="silent" --link=mysql:db $IMAGENAME
  docker logs $CONTAINER_NAME
  [ $? != 0 ] && error "Docker image build failed !" && exit 100
}

stop() {
  docker stop $CONTAINER_NAME
}

start() {
  docker start $CONTAINER_NAME
}

remove() {
  log "Removing previous container $CONTAINER_NAME" && \
      docker rm -f $CONTAINER_NAME &> /dev/null || true
}

log() {
  echo -e "$BLUE > $1 $NORMAL"
}

error() {
  echo ""
  echo -e "$RED >>> ERROR - $1$NORMAL"
}

help() {
  echo "-----------------------------------------------------------------------"
  echo "                      Available commands                              -"
  echo "-----------------------------------------------------------------------"
  echo -e -n "$BLUE"
  echo "   > build - Build the Docker image"
  echo "   > run - Start first time"
  echo "   > silen - Start first time and install Mahara silent"
  echo "   > stop - Stop $CONTAINER_NAME"
  echo "   > start - Start $CONTAINER_NAME"
  echo "   > remove - Remove $CONTAINER_NAME"
  echo "   > help - Display this help"
  echo -e -n "$NORMAL"
  echo "-----------------------------------------------------------------------"

}

# Output colors
NORMAL="\\033[0;39m"
RED="\\033[1;31m"
BLUE="\\033[1;34m"

$*
