#!/usr/bin/with-contenv sh

set -e

APPDIR=/usr/share/webapps/moodle
APPADMIN=${APPADMIN:-admin}
APPADMINPASS=${APPADMINPASS:-$(pwgen -s -1 8)}
APPADMINEMAIL=${APPADMINEMAIL:-admin@lochalhost.local}
APPDB=${APPDB:-moodle}
APPDBUSER=${APPDBUSER:-moodle}
APPDBPASS=${APPDBPASS:-$(pwgen -s -1 16)}
SALD=${SALD:-$(pwgen -s -1 16)}
WWWROOT=${WWWROOT:-/}
FULLNAME=${FULLNAME:-Moodle}
SHORTNAME=${SHORTNAME:-MOODLE}
SUMMARY=${SUMMARY:-Moodle}
DBUSER=${DBUSER:-$DB_ENV_DBUSER}
DBPASS=${DBPASS:-$DB_ENV_DBPASS}
DBHOST=${DBHOST:-db}
INSTALL=${INSTALL:-normal}

if [ -f /etc/nginx/sites-enabled/example.site ]; then
  rm /etc/nginx/sites-enabled/example.site
fi

if [ ! -f /etc/nginx/sites-enabled/moodle.site ]; then
  cp /etc/nginx/moodle.site /etc/nginx/sites-enabled/moodle.site
  chown www-data:www-data /etc/nginx/sites-enabled/moodle.site
fi

if [ $INSTALL = "silent" ]; then
  echo "Create database user $APPDBUSER and database $APPDB"
  until nc -z ${DBHOST} 3306; do sleep 1; echo "Waiting for DB to come up..."; done
  mysql -u ${DBUSER} --password=${DBPASS} -h ${DBHOST} <<-EOF
   CREATE DATABASE IF NOT EXISTS $APPDB CHARACTER SET utf8;
   GRANT ALL PRIVILEGES ON $APPDB.* TO $APPDBUSER IDENTIFIED BY '$APPDBPASS';
   FLUSH PRIVILEGES;
   USE $APPDB;
   SET SESSION sql_mode=STRICT_ALL_TABLES;
   SET GLOBAL innodb_file_per_table=1;
   SET GLOBAL innodb_file_format=Barracuda;
EOF

s6-envuidgid www-data php $APPDIR/admin/cli/install.php \
	--non-interactive \
	--agree-license \
	--lang=en \
	--wwwroot=http://localhost \
	--dataroot=/var/moodledata \
	--dbtype=mariadb \
	--dbhost=${DBHOST} \
	--dbuser=${APPDBUSER} \
	--dbpass=${APPDBPASS} \
	--dbport=3306 \
	--fullname=${FULLNAME} \
	--shortname=${SHORTNAME} \
	--summary=${SUMMARY} \
	--adminuser=${APPADMIN} \
	--adminpass=${APPADMINPASS} \
	--adminemail=${APPADMINEMAIL}
cp -ax $APPDIR/config.php $APPDIR/config/config.php
sed -i "s*http://localhost*${WWWROOT}*g" $APPDIR/config/config.php 
echo "\n[i] Set automatic configuration:\n  Admin = $APPADMIN \n  Pass = $APPADMINPASS \n  www_root:$WWWROOT\n---\n"
fi

if [ ! $WWWROOT = "/" ]; then
  if [ ! $WWWROOT = "/moodle" ]; then
    mv $APPDIR /usr/share/webapps/$WWWROOT
    chown www-data:www-data /usr/share/webapps/$WWWROOT
  fi
  sed -i "s*example.com*WWWROOT*g" $APPDIR/config/config.php
  sed -i "s*root /usr/share/webapps/moodle*root /usr/share/webapps*g" /etc/nginx/sites-enabled/moodle.site
fi

rm /etc/cont-init.d/moodle-firstrun
rm /usr/local/sbin/firstrun

exit 0
