#!/usr/bin/env bash
# ------------------------------------------------------------------
# [Christian-Maximilian Steier]
# Build a small AlpineLinux Docker image php version 7      
# ------------------------------------------------------------------

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NAMESPACE="maxder"

if [ $(uname -m) == "armv6l" ]; then
	DISTRO="rpi-alpine"
else
	DISTRO="alpine"
fi
sed -i "s*PLACEHOLDER*${DISTRO}*g" $DIR/Dockerfile

CONTAINER_NAME="php7"
IMAGENAME="${NAMESPACE}/${DISTRO}-${CONTAINER_NAME}:edge"

build() {
  docker build --rm -t $IMAGENAME .

  [ $? != 0 ] && error "Docker image build failed !" && exit 100
}

help() {
  echo "-----------------------------------------------------------------------"
  echo "                      Available commands                              -"
  echo "-----------------------------------------------------------------------"
  echo -e -n "$BLUE"
  echo "   > build - Build the Docker image"
  echo "   > help - Display this help"
  echo -e -n "$NORMAL"
  echo "-----------------------------------------------------------------------"

}

# Output colors
NORMAL="\\033[0;39m"
RED="\\033[1;31m"
BLUE="\\033[1;34m"

$*
