FROM maxder/PLACEHOLDER-base:edge
MAINTAINER Christian-Maxilian Steier

RUN echo "@maxder https://github.com/christiansteier/alpine-repo/raw/master" >> /etc/apk/repositories
RUN apk -U add --allow-untrusted \
	php@maxder \
	php-common@maxder \
	php-cli@maxder \
	php-fpm@maxder \
	php-json@maxder \ 
	php-zlib@maxder \
	php-xml@maxder \
	php-pdo@maxder \
	php-phar@maxder \
	php-openssl@maxder \
	php-pdo@maxder \
	php-pdo_mysql@maxder \
	php-mysqli@maxder \
	php-gd@maxder \
	php-iconv@maxder \
	php-mcrypt@maxder \
	php-curl@maxder \
	php-opcache@maxder \
	php-ctype@maxder \
	php-intl@maxder \
	php-bcmath@maxder \
	php-dom@maxder \
	php-xmlreader@maxder \
	php-cgi@maxder \
	php-pdo_pgsql@maxder \
	php-soap@maxder \
    	php-gettext@maxder \
	php-json@maxder \
	php-xmlrpc@maxder \
	php-posix@maxder \
	php-ftp@maxder

