#!/bin/sh

set -e

HUMHUB_DB=${HUMHUB_DB:-humhub}
HUMHUB_PASS=${HUMHUB_PASS:-$(pwgen -s -1 16)}
HUMHUB_SUBDIR=${HUMHUB_SUBDIR:-humhub}
HUMHUBDIR=/usr/share/webapps/$HUMHUB_SUBDIR
DBHOST=${DBHOST:-db}
DBADMIN=${DBADMIN:-$DB_ENV_DBUSER}
DBPASS=${DBPASS:-$DB_ENV_DBPASS}

if [ ! -z "$MYSQL_PORT_3306_TCP_ADDR" ]; then
	sed -i "s/.*dbhost.*/  'dbhost' => '$MYSQL_PORT_3306_TCP_ADDR',/" $OCDIR/config/config.php
fi

if [ -f /firstrun ]; then
if [ "`mysql -u $DBADMIN -p $DBPASS i-h $DBHOST -se'USE $HUMHUB_DB;' 2>&1`" == "" ]; then
        echo "$HUMHUB_DB exist"
        echo "So I expect a config.php under $HUMHUBDIR"
  else
        echo "Create database user $HUMHUB_DB and database $HUMHUB_DB"

        mysql -u $DBADMIN --password=$DBPASS -h $DBHOST <<-EOF
        CREATE DATABASE IF NOT EXISTS $HUMHUB_DB CHARACTER SET utf8 COLLATE utf8_general_ci;
        GRANT ALL PRIVILEGES ON $HUMHUB_DB.* TO '$HUMHUB_DB'@'%' IDENTIFIED BY '$HUMHUB_PASS';
        FLUSH PRIVILEGES;
EOF

  fi
  mv /usr/share/webapps/humhub /usr/share/webapps/PLACEHOLDER
  mv /usr/share/webapps/PLACEHOLDER $HUMHUBDIR
  sed -i "s*HUMHUB_SUBDIR*$HUMHUB_SUBDIR*g" /etc/nginx/conf.d/localhost.conf
  sed -i "s*HUMHUB_SUBDIR*$HUMHUB_SUBDIR*g" /etc/periodic/15min/humhub
  sed -i "s*HUMHUB_SUBDIR*$HUMHUB_SUBDIR*g" /etc/periodic/daily/humhub

  rm /firstrun

echo "---"
echo "Database = $HUMHUB_DB"
echo "Password = $HUMHUB_PASS"
echo "DB host = $DBHOST"
echo "---"

fi

chmod -R 755 /var/lib/nginx
chown -R nginx:www-data $HUMHUBDIR
chmod +x $HUMHUBDIR//protected/yii
chmod +x $HUMHUBDIR//protected/yii.bat
